# Generated by Django 3.2.4 on 2021-06-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
