# Generated by Django 3.2.4 on 2021-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0002_alter_cv_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
