# Generated by Django 3.2.4 on 2021-06-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0003_alter_cv_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
