# Generated by Django 3.2.4 on 2021-06-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mipagina', '0004_alter_cv_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('special_status', 'Puede ver todos los libros')]},
        ),
        migrations.AlterField(
            model_name='cv',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
