services:
    web:
        build: .
        #command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn proyecto1.wsgi -b 0.0.0.0:8000
        environment: 
            - ENVIROMENT=development
            - DEBUG=1
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51IyPt5ILM51eLq0kNKDXDERtMbgY8MHrHaJA7cAqeHaTHb75x4Yh5AEp6QVw3SeVQQdHOf7LJZK6wZi7R6P2ilR2000cykvNRo
            - STRIPE_TEST_SECRET_KEY=sk_test_51IyPt5ILM51eLq0kQoQfHRo6oYEyTbAoYXEmRm5PiDFxWTYFG0pzFtvg4xvSK2wa2Xnkt9Mg2Xt3v993nKHniI5s00R2oU8IAO
            
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:13
        
        environment: 
            POSTGRES_DB: "db"
            POSTGRES_HOST_AUTH_METHOD: "trust"
            
